# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0005_auto_20180306_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='david', max_length=50),
        ),
    ]
